import { mutation, query } from "./_generated/server";
import { v } from "convex/values";
import { requireRole, writeAudit, createNotification } from "./lib/auth";

const staff = ["support", "operator", "compliance", "admin"] as const;

export const overview = query({ args: {}, handler: async ctx => { await requireRole(ctx, [...staff]); const pendingKyc = await ctx.db.query("kycCases").withIndex("by_status", q => q.eq("status", "manual_review")).take(50); const reviewTransfers = await ctx.db.query("transfers").withIndex("by_status", q => q.eq("status", "review")).take(50); const failedTransfers = await ctx.db.query("transfers").withIndex("by_status", q => q.eq("status", "failed")).take(50); return { pendingKyc, reviewTransfers, failedTransfers }; }});
export const account = query({ args: { accountId: v.id("accounts") }, handler: async (ctx, { accountId }) => { await requireRole(ctx, [...staff]); const account = await ctx.db.get(accountId); if (!account) throw new Error("ACCOUNT_NOT_FOUND"); const user = await ctx.db.get(account.userId); const transactions = await ctx.db.query("transactions").withIndex("by_account", q => q.eq("accountId", accountId)).order("desc").take(100); return { account, user: user ? { _id: user._id, name: user.name, email: user.email, role: user.role, kycStatus: user.kycStatus, accountStatus: user.accountStatus } : null, transactions }; }});
export const transferQueue = query({ args: { status: v.optional(v.union(v.literal("review"), v.literal("processing"), v.literal("failed"), v.literal("completed"))) }, handler: async (ctx, args) => { await requireRole(ctx, [...staff]); return args.status ? await ctx.db.query("transfers").withIndex("by_status", q => q.eq("status", args.status!)).order("desc").take(100) : await ctx.db.query("transfers").order("desc").take(100); }});

export const resolveTransfer = mutation({ args: { transferId: v.id("transfers"), decision: v.union(v.literal("complete"), v.literal("fail")), note: v.string() }, handler: async (ctx, args) => {
  const { user, identity } = await requireRole(ctx, ["operator", "admin"]); const transfer = await ctx.db.get(args.transferId); if (!transfer) throw new Error("TRANSFER_NOT_FOUND"); if (!["review", "processing"].includes(transfer.status)) throw new Error("INVALID_TRANSFER_STATE");
  const now = Date.now();
  if (args.decision === "complete") {
    if (transfer.status !== "review" || !transfer.destinationAccountId) throw new Error("EXTERNAL_SETTLEMENT_REQUIRES_PROVIDER_CONFIRMATION");
    const source = await ctx.db.get(transfer.sourceAccountId); const destination = await ctx.db.get(transfer.destinationAccountId); if (!source || !destination) throw new Error("TRANSFER_ACCOUNTS_NOT_FOUND"); if (source.status !== "active" || destination.status !== "active") throw new Error("ACCOUNT_UNAVAILABLE"); if (source.availableBalance < transfer.amount) throw new Error("INSUFFICIENT_FUNDS_AT_REVIEW");
    await ctx.db.patch(source._id,{balance:source.balance-transfer.amount,availableBalance:source.availableBalance-transfer.amount,updatedAt:now}); await ctx.db.patch(destination._id,{balance:destination.balance+transfer.amount,availableBalance:destination.availableBalance+transfer.amount,updatedAt:now});
    const debit=await ctx.db.insert("transactions",{accountId:source._id,userId:source.userId,amount:transfer.amount,currency:source.currency,category:"Transfer",type:"debit",status:"completed",description:`Transfer to ${transfer.beneficiaryName}`,reference:transfer.reference,createdAt:now,updatedAt:now}); const credit=await ctx.db.insert("transactions",{accountId:destination._id,userId:destination.userId,amount:transfer.amount,currency:source.currency,category:"Transfer",type:"credit",status:"completed",description:`Transfer from Crestline customer`,reference:transfer.reference,createdAt:now,updatedAt:now}); await ctx.db.insert("ledgerEntries",{transactionId:debit,accountId:source._id,direction:"debit",amount:transfer.amount,currency:source.currency,createdAt:now}); await ctx.db.insert("ledgerEntries",{transactionId:credit,accountId:destination._id,direction:"credit",amount:transfer.amount,currency:source.currency,createdAt:now}); await ctx.db.patch(transfer._id,{status:"completed",updatedAt:now}); await createNotification(ctx,transfer.userId,"transaction","Transfer approved",`${transfer.amount.toFixed(2)} ${transfer.currency} was approved after manual risk review.`,`transfer-approved:${transfer._id}`); await createNotification(ctx,destination.userId,"transaction","Incoming transfer",`${transfer.amount.toFixed(2)} ${transfer.currency} was received.`,`transfer-credit:${transfer.reference}`); await writeAudit(ctx,user._id,identity.subject,"transfer.manually_completed","transfer",transfer._id,{note:args.note.slice(0,500)}); return await ctx.db.get(transfer._id);
  }
  await ctx.db.patch(transfer._id,{status:"failed",failureCode:"MANUAL_REJECT",failureMessage:args.note.slice(0,500),updatedAt:now}); await writeAudit(ctx,user._id,identity.subject,"transfer.manually_failed","transfer",transfer._id,{note:args.note.slice(0,500)}); await createNotification(ctx,transfer.userId,"transaction","Transfer failed",args.note.slice(0,500),`transfer-failed:${transfer._id}`); return await ctx.db.get(transfer._id);
}});

export const setAccountStatus = mutation({ args: { accountId: v.id("accounts"), status: v.union(v.literal("active"),v.literal("frozen"),v.literal("closed")), reason: v.string() }, handler: async (ctx,args)=>{const {user,identity}=await requireRole(ctx,["operator","admin"]);const account=await ctx.db.get(args.accountId);if(!account)throw new Error("ACCOUNT_NOT_FOUND");if(account.status==="closed"&&args.status!=="closed")throw new Error("CLOSED_ACCOUNT_IMMUTABLE");await ctx.db.patch(account._id,{status:args.status,updatedAt:Date.now()});await writeAudit(ctx,user._id,identity.subject,"account.status_changed","account",account._id,{status:args.status,reason:args.reason.slice(0,500)});await createNotification(ctx,account.userId,"account",`Account ${args.status}`,args.reason.slice(0,500),`account-status:${account._id}:${args.status}`);return await ctx.db.get(account._id);}});
export const setUserRole = mutation({ args: { userId: v.id("users"), role: v.union(v.literal("customer"),v.literal("support"),v.literal("operator"),v.literal("compliance"),v.literal("admin")) }, handler: async (ctx,args)=>{const {user,identity}=await requireRole(ctx,["admin"]);if(args.userId===user._id)throw new Error("SELF_ROLE_CHANGE_NOT_ALLOWED");const target=await ctx.db.get(args.userId);if(!target)throw new Error("USER_NOT_FOUND");await ctx.db.patch(target._id,{role:args.role,updatedAt:Date.now()});await writeAudit(ctx,user._id,identity.subject,"user.role_changed","user",target._id,{role:args.role});return await ctx.db.get(target._id);}});
