"use client";
import Link from "next/link";
import { useState } from "react";
import { Authenticated, AuthLoading, Unauthenticated, useMutation, useQuery } from "convex/react";
import { UserButton } from "@clerk/nextjs";
import { api } from "@/convex/_generated/api";

function Operations(){
 const [status,setStatus]=useState(""); const overview=useQuery(api.admin.overview); const queue=useQuery(api.compliance.queue,{status:"manual_review"}); const review=useMutation(api.compliance.review); const resolve=useMutation(api.admin.resolveTransfer);
 const doKyc=async(id:any,decision:"verified"|"rejected")=>{try{await review({caseId:id,decision,note:decision==="verified"?"Reviewed required evidence and approved.":"Reviewed submission and rejected it; customer must resubmit."});setStatus(`KYC ${decision}`)}catch(e){setStatus(e instanceof Error?e.message:"Action failed")}};
 const settle=async(id:any,decision:"complete"|"fail")=>{try{await resolve({transferId:id,decision,note:decision==="complete"?"Manual risk review completed and internal settlement approved.":"Operations review rejected the transfer."});setStatus(decision==="complete"?"Transfer completed":"Transfer rejected")}catch(e){setStatus(e instanceof Error?e.message:"Action failed")}};
 if(!overview||!queue)return <div className="container" style={{paddingTop:40}}>Loading operations…</div>;
 return <main className="main" style={{maxWidth:1400,margin:"0 auto"}}><div className="topbar"><div><Link href="/dashboard" className="brand">Crestline <span>Capital</span></Link><h1>Operations & compliance</h1></div><UserButton/></div>{status&&<div className="card" style={{padding:14,marginBottom:16}}>{status}</div>}<div className="grid grid-3"><div className="card stat"><div className="muted">KYC manual review</div><div className="value">{queue.length}</div></div><div className="card stat"><div className="muted">Transfer review</div><div className="value">{overview.reviewTransfers.length}</div></div><div className="card stat"><div className="muted">Failed transfers</div><div className="value">{overview.failedTransfers.length}</div></div></div><section className="section"><h2>KYC queue</h2><div className="card" style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Case</th><th>User</th><th>Status</th><th>Action</th></tr></thead><tbody>{queue.map(k=><tr key={k._id}><td>{String(k._id).slice(-8)}</td><td>{String(k.userId).slice(-8)}</td><td>{k.status}</td><td><button className="btn-primary" onClick={()=>doKyc(k._id,"verified")}>Approve</button> <button className="btn-secondary" onClick={()=>doKyc(k._id,"rejected")}>Reject</button></td></tr>)}</tbody></table></div></section><section className="section"><h2>Transfer review</h2><div className="card" style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Reference</th><th>Amount</th><th>Risk</th><th>Action</th></tr></thead><tbody>{overview.reviewTransfers.map(t=><tr key={t._id}><td>{t.reference}</td><td>{t.amount.toFixed(2)} {t.currency}</td><td>{t.riskScore} · {t.riskReasons.join(", ")}</td><td><button className="btn-primary" onClick={()=>settle(t._id,"complete")}>Approve</button> <button className="btn-secondary" onClick={()=>settle(t._id,"fail")}>Reject</button></td></tr>)}</tbody></table></div></section><p className="muted" style={{fontSize:13}}>Only internal Crestline transfers can be settled here. External settlement remains blocked until a regulated payment provider confirms the rail transaction.</p></main>
}
export default function Admin(){return <><AuthLoading><div className="container" style={{paddingTop:40}}>Authenticating…</div></AuthLoading><Unauthenticated><div className="container" style={{paddingTop:40}}><Link href="/login" className="btn-primary">Sign in</Link></div></Unauthenticated><Authenticated><Operations/></Authenticated></>}
