"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Dashboard(){
  const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false);
  useEffect(()=>{ fetch("/api/demo").then(async r=>{const x=await r.json(); if(!r.ok) throw new Error(x.error); setData(x)}).catch(e=>setError(e.message)).finally(()=>setLoading(false)); },[]);
  const card=data?.cards?.[0]; const accounts=data?.accounts||[]; const transactions=data?.transactions||[]; const total=accounts.reduce((s:number,a:any)=>s+a.balance,0);
  async function toggleCard(){ if(!card)return; setBusy(true); try { const r=await fetch("/api/demo/card",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({cardId:card._id})}); const x=await r.json(); if(!r.ok) throw new Error(x.error); setData((d:any)=>({...d,cards:d.cards.map((c:any)=>c._id===card._id?{...c,isFrozen:x.frozen}:c)})); } catch(e:any){setError(e.message)} finally{setBusy(false)} }
  return <div className="dashboard">
    <aside className="sidebar"><Link href="/" className="brand">Crestline <span>Capital</span></Link><nav><a className="active" href="#overview">Overview</a><a href="#accounts">Accounts</a><a href="#transactions">Transactions</a><a href="#cards">Cards</a><a href="#transfers">Transfers</a><a href="#security">Security</a></nav><div className="card" style={{padding:14,marginTop:24}}><div className="muted" style={{fontSize:12}}>DEMO PROFILE</div><strong>{data?.user?.name||"Demo Customer"}</strong><div className="muted" style={{fontSize:12,marginTop:4}}>KYC verified · 2FA enabled</div></div></aside>
    <main className="main"><div className="topbar"><div><div className="muted">Sunday, September 6, 2026</div><h1 style={{margin:"4px 0",fontSize:30}}>Good morning.</h1></div><Link href="/" className="btn-secondary">Sign out</Link></div>
      {loading&&<div className="card" style={{padding:20}}>Loading secure demo data from Convex…</div>}{error&&<div className="card" style={{padding:20,borderColor:"#fb7185"}}><strong>Convex connection required.</strong><div className="muted" style={{marginTop:6}}>{error}</div></div>}
      {!loading&&!error&&<><section id="overview" className="grid grid-3"><div className="card balance" style={{gridColumn:"span 2"}}><div className="muted">Total balance</div><div className="amount">${total.toLocaleString("en-US",{minimumFractionDigits:2})}</div><div className="muted">Across {accounts.length} accounts · USD</div></div><div className="card stat"><div className="muted">Recent activity</div><div className="value">{transactions.length}</div><div className="muted">Ledger entries shown</div></div></section>
      <section id="accounts" className="section"><h2>Accounts</h2><div className="grid grid-2">{accounts.map((a:any)=><div className="card stat" key={a._id}><div className="muted">{a.type[0].toUpperCase()+a.type.slice(1)} · {a.accountNumberMasked}</div><div className="value">${a.balance.toLocaleString("en-US",{minimumFractionDigits:2})}</div><div className="muted">Available balance · {a.status}</div></div>)}</div></section>
      <section id="transactions" className="section"><div className="topbar"><div><h2>Recent transactions</h2><div className="muted">Latest Convex ledger activity</div></div></div><div className="card" style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Description</th><th>Category</th><th>Amount</th></tr></thead><tbody>{transactions.map((t:any)=><tr key={t._id}><td>{t.description}</td><td className="muted">{t.category}</td><td className={t.type==="credit"?"amount-positive":"amount-negative"}>{t.type==="credit"?"+":"-"}${t.amount.toLocaleString("en-US",{minimumFractionDigits:2})}</td></tr>)}</tbody></table></div></section>
      <section id="cards" className="section"><h2>Card controls</h2><div className="card" style={{padding:24,display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,flexWrap:"wrap"}}><div><div style={{fontWeight:800}}>{card?.brand||"Crestline"} •••• {card?.last4||"4821"}</div><div className="muted">Expires {String(card?.expiryMonth||8).padStart(2,"0")}/{String(card?.expiryYear||2029).slice(-2)} · {card?.isFrozen?"Frozen":"Active"}</div></div><button disabled={busy} className={card?.isFrozen?"btn-primary":"btn-secondary"} onClick={toggleCard}>{busy?"Updating…":card?.isFrozen?"Unfreeze card":"Freeze card"}</button></div></section>
      <section id="transfers" className="section"><h2>Transfers</h2><div className="card" style={{padding:24}}><p className="muted">Convex validates the demo account owner and available balance, then records a simulated transfer, transaction, ledger entry and notification. No real funds are moved.</p></div></section>
      <section id="security" className="section"><h2>Security & compliance</h2><div className="grid grid-3"><div className="card stat"><strong>256-bit TLS</strong><div className="muted">Transport protection</div></div><div className="card stat"><strong>2FA</strong><div className="muted">Enabled for demo profile</div></div><div className="card stat"><strong>KYC</strong><div className="muted">Verified demo state</div></div></div></section></>}
    </main>
  </div>
}