"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Authenticated, AuthLoading, Unauthenticated, useMutation, useQuery } from "convex/react";
import { UserButton } from "@clerk/nextjs";
import { api } from "@/convex/_generated/api";

function DashboardContent(){
  const [setupError,setSetupError]=useState(""); const [transferOpen,setTransferOpen]=useState(false); const [destination,setDestination]=useState(""); const [name,setName]=useState(""); const [amount,setAmount]=useState(""); const [transferMessage,setTransferMessage]=useState("");
  const provision=useMutation(api.users.provision); const ensureAccount=useMutation(api.banking.ensureDefaultAccount); const toggleCard=useMutation(api.banking.toggleCard); const createTransfer=useMutation(api.banking.transfer); const markAllRead=useMutation(api.notifications.markAllRead);
  const data: any=useQuery(api.banking.dashboard);
  useEffect(()=>{(async()=>{try{await provision({});await ensureAccount({});}catch(e){setSetupError(e instanceof Error?e.message:"Unable to initialize account")}})()},[provision,ensureAccount]);
  const submitTransfer=async(e:React.FormEvent)=>{e.preventDefault();setTransferMessage("");try{if(!data?.accounts[0])throw new Error("No source account");const result=await createTransfer({sourceAccountId:data.accounts[0]._id,beneficiaryAccount:destination.trim(),beneficiaryName:name.trim(),amount:Number(amount),idempotencyKey:crypto.randomUUID()+crypto.randomUUID()});setTransferMessage(result?.status==="completed"?"Transfer completed successfully.":result?.status==="review"?"Transfer submitted for manual risk review.":"Transfer submitted.");setDestination("");setName("");setAmount("")}catch(e){setTransferMessage(e instanceof Error?e.message:"Transfer failed")}};
  if(setupError)return <div className="card" style={{padding:24}}><strong>Account setup failed</strong><p className="muted">{setupError}</p></div>;
  if(!data)return <div className="card" style={{padding:24}}>Loading your secure banking workspace…</div>;
  const total=data.accounts.reduce((s:number,a:any)=>s+a.balance,0); const unread=data.notifications.filter((n:any)=>!n.read).length;
  return <div className="dashboard"><aside className="sidebar"><Link href="/" className="brand">Crestline <span>Capital</span></Link><nav><a className="active" href="#overview">Overview</a><a href="#accounts">Accounts</a><a href="#transactions">Transactions</a><a href="#cards">Cards</a><a href="#transfers">Transfers</a><a href="#security">Security</a>{["admin","compliance","operator","support"].includes(data.user.role)&&<Link href="/admin">Operations</Link>}<Link href="/kyc">KYC verification</Link></nav><div className="card" style={{padding:14,marginTop:24}}><div className="muted" style={{fontSize:12}}>ACCOUNT</div><strong>{data.user.name}</strong><div className="muted" style={{fontSize:12,marginTop:4}}>{data.user.kycStatus.replace("_"," ")} · {data.user.role}</div></div></aside>
  <main className="main"><div className="topbar"><div><div className="muted">Crestline Capital</div><h1 style={{margin:"4px 0",fontSize:30}}>Financial overview</h1></div><div style={{display:"flex",gap:12,alignItems:"center"}}><button className="btn-secondary" onClick={()=>markAllRead()}>{unread?`${unread} notifications`:"Notifications"}</button><UserButton /></div></div>
  <section id="overview" className="grid grid-3"><div className="card balance" style={{gridColumn:"span 2"}}><div className="muted">Total balance</div><div className="amount">${total.toLocaleString("en-US",{minimumFractionDigits:2})}</div><div className="muted">Across {data.accounts.length} accounts · USD</div></div><div className="card stat"><div className="muted">KYC status</div><div className="value" style={{fontSize:24}}>{data.user.kycStatus.replace("_"," ")}</div><div className="muted">Transfers require verified identity</div></div></section>
  <section id="accounts" className="section"><h2>Accounts</h2><div className="grid grid-2">{data.accounts.map((a:any)=><div className="card stat" key={a._id}><div className="muted">{a.type[0].toUpperCase()+a.type.slice(1)} · {a.accountNumberMasked}</div><div className="value">${a.balance.toLocaleString("en-US",{minimumFractionDigits:2})}</div><div className="muted">Available ${a.availableBalance.toLocaleString("en-US",{minimumFractionDigits:2})} · {a.status}</div></div>)}</div></section>
  <section id="transactions" className="section"><div className="topbar"><div><h2>Recent transactions</h2><div className="muted">Live Convex ledger activity</div></div></div><div className="card" style={{overflowX:"auto"}}><table className="table"><thead><tr><th>Description</th><th>Status</th><th>Amount</th></tr></thead><tbody>{data.transactions.map((t:any)=><tr key={t._id}><td>{t.description}</td><td className="muted">{t.status}</td><td className={t.type==="credit"?"amount-positive":"amount-negative"}>{t.type==="credit"?"+":"-"}${t.amount.toLocaleString("en-US",{minimumFractionDigits:2})}</td></tr>)}</tbody></table></div></section>
  <section id="cards" className="section"><h2>Card controls</h2><div className="grid grid-2">{data.cards.map((card:any)=><div className="card" style={{padding:24,display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,flexWrap:"wrap"}} key={card._id}><div><div style={{fontWeight:800}}>{card.brand} •••• {card.last4}</div><div className="muted">Expires {String(card.expiryMonth).padStart(2,"0")}/{String(card.expiryYear).slice(-2)} · {card.isFrozen?"Frozen":"Active"}</div></div><button className={card.isFrozen?"btn-primary":"btn-secondary"} onClick={()=>toggleCard({cardId:card._id})}>{card.isFrozen?"Unfreeze card":"Freeze card"}</button></div>)}</div></section>
  <section id="transfers" className="section"><div className="topbar"><div><h2>Transfers</h2><div className="muted">Internal Crestline transfers settle atomically. External rails require a configured provider.</div></div><button className="btn-primary" onClick={()=>setTransferOpen(!transferOpen)}>New transfer</button></div>{transferOpen&&<form className="card" style={{padding:24,display:"grid",gap:12,maxWidth:620}} onSubmit={submitTransfer}><label>Recipient account number<input className="input" value={destination} onChange={e=>setDestination(e.target.value)} inputMode="numeric" required /></label><label>Recipient name<input className="input" value={name} onChange={e=>setName(e.target.value)} required /></label><label>Amount<input className="input" value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0.01" step="0.01" required /></label><button className="btn-primary" type="submit">Submit transfer</button>{transferMessage&&<div className="muted">{transferMessage}</div>}</form>}</section>
  <section id="security" className="section"><h2>Security & compliance</h2><div className="grid grid-3"><div className="card stat"><strong>Clerk + Convex JWT</strong><div className="muted">Authenticated backend requests</div></div><div className="card stat"><strong>Server-side RBAC</strong><div className="muted">Sensitive operations enforced in Convex</div></div><div className="card stat"><strong>Audit trail</strong><div className="muted">Security and financial events recorded</div></div></div></section></main></div>
}
export default function Dashboard(){return <><AuthLoading><main className="container" style={{paddingTop:60}}>Authenticating…</main></AuthLoading><Unauthenticated><main className="container" style={{paddingTop:60}}><Link href="/login" className="btn-primary">Sign in required</Link></main></Unauthenticated><Authenticated><DashboardContent/></Authenticated></>}
